# Deployed instance
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

springdoc:
  api-docs.enabled: ${DEMO_ENABLED:true}
  swagger-ui.enabled: ${DEMO_ENABLED:true}
server:
  forward-headers-strategy: framework

logging:
  structured:
    format:
      console: ecs          # one JSON object per log line
  level:
    root: INFO
app:
  jwt:
    secret: ${JWT_SECRET}
  demo:
    enabled: ${DEMO_ENABLED:true}